FROM 4xxi/php-pgsql:flex

# To add additional packages and php extensions uncomment the following lines and add required dependencies
# Check https://hub.docker.com/_/php/ for examples and documentation

#RUN apt-get update && apt-get install -y \
#    lib_name_1 \
#    lib_name_2 \
#    && docker-php-ext-install \
#    ext_name_1 \
#    ext_name_2